### ISSUE TITLE
App crashes when trying to chose whitlisted contacts

### ISSUE THREAD

**Issue by karano-techie** [xfarrow/locatemydevice#3]
Steps to reproduce - setup password then add whitelisted contacts - app crashes.
Tested on Android v12
Motorola g
App version 1.0.2
refer  [crash logs](https://cloud.disroot.org/s/WQq5kGzRNb5MyXR)

**Comment by xfarrow** [comment]
Thank you for your submission, I will work on it as soon as possible.

**Comment by xfarrow** [comment]
For some reason, on my Android12 emulator, the issue does not arise. I will keep looking into the issue, in the meantime, would you mind to share how the contact you're trying to add looks like? (no need to share the real phone number, I just would like to know if it contains some characters that are unrecognized by the app).
Does it crash on every phone number?

Thank you for your patience.

**Comment by karano-techie** [comment]
> Does it crash on every phone number?

Yes it crashes on every phone number.
 
I use simple contacts as my phonebook.  On pressing the '+' sign in whitelist menu , i chose the 'simple contacts app' and i am redirected to the list view of my contacts appearing by their names. If i then select any contact , it redirects back to 'locate my phone' app but still has the whitelisted contacts empty. Then it will crash a second after it.

Maybe the problem is with simple contacts ? coz i think it does not allow other apps to read the contacts. 
i'll try to use another contacts app.

Also if i could add numbers manually, would work around it.

**Comment by xfarrow** [comment]
Yes it's definitely the use of the app "Simple Contacts" making the app crash. I do not know wether it's my or their issue. I will investigate into it.

In the meantime, I will add the possibility to manually add the phone number, thank you for the suggestion!

**Comment by karano-techie** [comment]
Thanks for making this project. 👍

I have almost the same vision and requirement for such a service.

**Comment by xfarrow** [comment]
The crash shouldn't happen any longer and I added the functionality to manually add whitelisted phone number.

Unfortunately it is still impossible to add a contact from the app "Simple Contacts". I opened [an issue](https://github.com/SimpleMobileTools/Simple-Contacts/issues/905) in their repo because the problem seems (according to me) to be on their part

**Comment by karano-techie** [comment]
Thanks for adding manual functionality , it solved the problem for me without needing to install other contacts app.
I also think the problem is on simple contacts side.

**Comment by xfarrow** [comment]
Now we are able to get contacts from Simple-Contacts as well! Just uploaded the release.
We don't need to fix this toast 'cause won't be shown anymore (hopefully) :)
